In [ ]:
import boto3
import awswrangler as wr
import pandas as pd

boto3.setup_default_session(region_name="us-east-2")

DATABASE = "cyber_security_db"

def sql(query: str) -> pd.DataFrame:
    return wr.athena.read_sql_query(
        sql=query,
        database=DATABASE,
        ctas_approach=False,
    )

In [5]:
sql("SELECT * FROM vulnerabilidade LIMIT 10")

c:\Users\Lethicia Asevedo\Desktop\Cyber_Security_Case\venv\Lib\site-packages\awswrangler\athena\_read.py:602: UserWarning: No `s3_output` was provided and the workgroup has no ResultConfiguration set. Falling back to the default bucket `aws-athena-query-results-{account}-{region}`. Because S3 bucket names are global, relying on this predictable default is discouraged: pass an explicit `s3_output`, or configure a workgroup with EnforceWorkGroupConfiguration=true and a ResultConfiguration.
  s3_output = _get_s3_output(s3_output=s3_output, wg_config=wg_config, boto3_session=boto3_session)

,vuln_id,ativo_id,severidade,origem,data_abertura,data_correcao,status,cvss_score
0,V00001,A0078,Baixa,Cloud Security,21/03/2026,<NA>,Em tratamento,2.8
1,V00002,A0060,Alta,Qualys,01/06/2026,<NA>,Em tratamento,7.5
2,V00003,A0080,Alta,Veracode,18/08/2026,<NA>,Aberta,1.7
3,V00004,A0086,Alta,Qualys,16/06/2026,<NA>,Aberta,2.5
4,V00005,A0089,Alta,Cloud Security,12/02/2026,<NA>,Em tratamento,4.4
5,V00006,A0025,Crítica,Cloud Security,02/05/2026,<NA>,Aberta,8.9
6,V00007,A0061,Média,Veracode,29/03/2026,<NA>,Aceita,5.9
7,V00008,A0189,Baixa,Pentest,12/01/2026,<NA>,Aceita,4.4
8,V00009,A0186,Alta,Veracode,15/03/2026,<NA>,Em tratamento,3.1
9,V00010,A0173,Baixa,Veracode,16/09/2026,<NA>,Em tratamento,1.7

In [6]:
sql("SELECT * FROM ativos LIMIT 10")

c:\Users\Lethicia Asevedo\Desktop\Cyber_Security_Case\venv\Lib\site-packages\awswrangler\athena\_read.py:602: UserWarning: No `s3_output` was provided and the workgroup has no ResultConfiguration set. Falling back to the default bucket `aws-athena-query-results-{account}-{region}`. Because S3 bucket names are global, relying on this predictable default is discouraged: pass an explicit `s3_output`, or configure a workgroup with EnforceWorkGroupConfiguration=true and a ResultConfiguration.
  s3_output = _get_s3_output(s3_output=s3_output, wg_config=wg_config, boto3_session=boto3_session)

,col0,col1,col2,col3,col4,col5,col6
0,ativo_id,sistema,criticidade,dominio,ambiente,localidade,status_ativo
1,A0001,Sistema_1,Crítica,Dominio_2,Homologação,São Paulo,Em desativação
2,A0002,Sistema_2,Média,Dominio_3,Produção,São Paulo,Em desativação
3,A0003,Sistema_3,Média,Dominio_4,Homologação,São Paulo,Ativo
4,A0004,Sistema_4,Alta,Dominio_5,Homologação,Campinas,Ativo
5,A0005,Sistema_5,Alta,Dominio_6,Produção,Recife,Ativo
6,A0006,Sistema_6,Baixa,Dominio_7,Produção,São Paulo,Ativo
7,A0007,Sistema_7,Baixa,Dominio_8,Produção,São Paulo,Ativo
8,A0008,Sistema_8,Alta,Dominio_9,Produção,São Paulo,Ativo
9,A0009,Sistema_9,Baixa,Dominio_10,Desenvolvimento,Recife,Ativo